apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openvscode-server

commonLabels:
  app: openvscode-server

configMapGenerator:
  - name: openvscode-server-config
    files:
      - config.yml

bases:
  - ./base
