apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvscode-server-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
